name: extended-ci

# FIXME only run on master when done testing
on:
  push:
    branches: [ master, aj-basic-github-actions ]

jobs:
  debian-CI:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        container: ['ubuntu:16.04', 'ubuntu:18.04', 'ubuntu:20.04', 'debian:testing', 'debian:10', 'debian:9']
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Update system/tooling
      run: DEBIAN_FRONTEND=noninteractive apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y gcc curl git libglib2.0-0
    - name: Run CI
      run: SCT_INSTALL_TYPE="in-place" ./.ci.sh

  redhat-CI:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        container: ['centos:8', 'centos:7', 'fedora:33', 'fedora:32', 'fedora:31']
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Update system/tooling
      run: yum update -y && yum install -y gcc curl git which
    - name: Run CI
      run: SCT_INSTALL_TYPE="in-place" ./.ci.sh

  macOS-CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        os: [macos-11.0, macos-10.15]
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Run CI
      run: SCT_INSTALL_TYPE="in-place" ./.ci.sh

  windows-CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        os: [windows-2019, windows-2016]
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-18.04
        update: true
        additional-packages:
          gcc
          git
          curl
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Run CI
      run: SCT_INSTALL_TYPE="in-place" ./.ci.sh

  archlinux-CI:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        container: ['archlinux']
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Update system/tooling
      run: pacman -Sy --noconfirm which gcc git curl
    - name: Run CI
      run: SCT_INSTALL_TYPE="in-place" ./.ci.sh
