name: simple-ci

on:
  push:
    branches: [ aj-basic-github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  debian-CI:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        container: ['ubuntu:16.04', 'ubuntu:18.04', 'ubuntu:20.04']
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Update system
      run: apt update -y
    - name: Install tooling
      run: DEBIAN_FRONTEND=noninteractive apt install -y gcc curl git libglib2.0-0  # for pyqt5 TODO investigate libglib2 requirement
    - name: Run CI
      run: SCT_INSTALL_TYPE="in-place" ./.ci.sh

  redhat-CI:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        container: ['centos:8', 'centos:7']
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Update system
      run: yum update -y
    - name: Install tooling
      run: yum install -y gcc curl git which
    - name: Run CI
      run: SCT_INSTALL_TYPE="in-place" ./.ci.sh

  macOS-CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        os: [macos-11.0, macos-10.15]
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Run CI
      run: SCT_INSTALL_TYPE="in-place" ./.ci.sh

  windows-CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # prevent cancellation of all jobs is one fails
      matrix:
        os: [windows-2019, windows-2016]
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Instal WSL
      run: choco install wsl-ubuntu-1804 -y --ignore-checksums
    - name: Enter WSL
      run: wsl
    - name: Update system/tooling
      run: DEBIAN_FRONTEND="noninteractive" WSLENV=DEBIAN_FRONTEND apt-get update && apt-get install -y gcc git curl
    - name: Run CI
      run: SCT_INSTALL_TYPE="in-place" wsl ./.ci.sh